receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
#        endpoint: "0.0.0.0:55681"
#  filelog:
#    include:
#      - ./logs.log
##    operators:
##      - type: regex_parser
##        regex: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (?P<sev>[A-Z]*) (?P<msg>.*)$'
##        timestamp:
##          parse_from: attributes.time
##          layout: '%Y-%m-%d %H:%M:%S'
##        severity:
##          parse_from: attributes.sev
#    multiline:
#      line_start_pattern: ^Exception



exporters:
  logging:
    loglevel: debug



  elasticsearch:
    endpoints: [ "https://es01:9200" ]
    traces_index: "traces-app"
    logs_index: "logs-app"
    user: elastic
    password: changeme
    tls:
      insecure_skip_verify: true

#  otlp/elasticsearch:
#    endpoint: "https://es01:9200"
#    timeout: 10s
#    tls:
#      insecure: false
#      insecure_skip_verify: true


processors:
  batch:
    timeout: 10s
    send_batch_size: 256
    send_batch_max_size: 2048

  transform:
    error_mode: ignore
    log_statements:
      - context: log
#        conditions:
#          - attributes["usecase"] != null
        statements:
          - set(attributes["usecase"], Split(attributes["usecase"], ","))

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ batch, transform ]
      exporters: [ logging, elasticsearch]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [ logging, elasticsearch]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [ logging, elasticsearch]
